version: "3.3"

services:
    db:
        image: postgres:10
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=sosecureitsfunny
            #- PGDATA=/var/lib/postgresql/data/pgdata